### ISSUE TITLE
Screencast vs. Sample

### ISSUE THREAD

**Issue by grgcombs** [appunite/CLCascade#1]
Your screencast looks great, with nice shadows and overall visual appeal.   The sample you provide didn't contain any of that.  Would you be interested in extending your sample a little to show us how you did it?

**Comment by emilwojtaszek** [comment]
We're working on a new version, which appears at the end of next week. Version will contain an extensive example.

**Comment by grgcombs** [comment]
Great!  I look forward to it.

**Comment by grgcombs** [comment]
Love the new examples

**Comment by emilwojtaszek** [comment]
Check last commit - I updated example.You can change offset property and page width of single view.

/*
- Offset of pages from left boarder. Default 66.0f
  */
  @property(nonatomic) CGFloat offset;

/*
- You can change page width, default (1024.0 - offset) / 2.0, so
- in landscape mode two pages fit properly
  */
  @property(nonatomic) CGFloat pageWidth;

**Comment by grgcombs** [comment]
Thanks Emil!!!
