### ISSUE TITLE
Crash Dealloc CLSPlitCascadeView on Memory Warning

### ISSUE THREAD

**Issue by pmilanez** [appunite/CLCascade#10]
HI Guys, great lib!!

I'm just having some problems with Memory Warning. 

When I create a CLSplitCascadeViewController using a NIB file and the app receives a Memory Warning it crashes at the end off the dealloc method on CLSplitCascadeView.

But, If I create a CLSplitCascadeViewController via code using the init method everything works on memory warning, but only the categories view is touchable, the rest does not receive any touch.

BTW, i'm using ARC and everything is working very well!

Thanks!

**Comment by pmilanez** [comment]
Ok, the problem about the touch was resolved.

On loadView method on CLSplitCascadeViewController was missing an association with the VIEW and the Controller

```
CLSplitCascadeView* view_ = [[CLSplitCascadeView alloc] init];
view_.splitCascadeViewController = self;
self.view = view_;
[view_ setCategoriesView: self.categoriesViewController.view];
[view_ setCascadeView: self.cascadeNavigationController.view];
```

But, i'm still having problems with the Memory Warning crash with BAD_ACESS

**Comment by pmilanez** [comment]
Everything works again if I commented the line that calls [super didReceiveMemoryWarning]; at CLSplitCascadeViewController.

I know that is not the right solution, but now when the app receives a warning does not crash.

**Comment by kwojtaszek** [comment]
can you share some code of your app or write an example to reproduce this bug? Call stack would help a lot also.

Thanks
Karol
AppUnite.com

**Comment by pmilanez** [comment]
I will create a project this weekend and upload. I think is maybe something with ARC. I had forked the project and converted to ARK with some modifications. You can start by there, if you want.

Thanks for the feedback!

**Comment by emilwojtaszek** [comment]
fixed ;p
