### ISSUE TITLE
ScrollView stops working on iOS 5

### ISSUE THREAD

**Issue by ethanmick** [appunite/CLCascade#11]
So, I've only been able to really make this happen on iOS 5.  Launch the app, and tap on a Category to load the first ExampleTableViewController on the stack.  You do _not_ need to load a second page on the stack (so if you haven't patched the iOS 5 bug yet, you don't need to).  Then, move the ExampleTableViewController back and forth a lot.  Fast, speedy, quick, jerk it around, bounce it back and forth.

At one point, the ScrollView stops reacting.  I can "select" a new category.  I can "select" something from the ExampleTableViewController, but it no longer moves when I scroll back and forth horizontally.  Pushing new pages on the stack works, (if the bug has been fixed), but you can't scroll between the pages.

Thoughts?  I've been looking into it, but I can't pinpoint exactly what is going on.

**Comment by emilwojtaszek** [comment]
in master branch ios5 is now supported ;)
