### ISSUE TITLE
Draggable viewcontroller

### ISSUE THREAD

**Issue by robderijk** [appunite/CLCascade#13]
Hi,

in your screencast I see a draggable viewcontroller (when you press the settings button and the google maps view controller opens). I can't find it anywhere in the examples but I like to use it in my app. Is it open source or where can I find more information about it?

Thanks!

**Comment by emilwojtaszek** [comment]
It's not part of this project, but it's very easy to do. I've just added UIPanGestureRecognizer to bar, and then in delegate method I update position of view:
- (void) mapViewDidRecivePagGesture:(UIPanGestureRecognizer*)panGestureRecognizer {
  
  CGRect frame = self.view.bounds;
  CGPoint point = [panGestureRecognizer locationInView:self.view];
  CGFloat properPosition = frame.size.height*0.75;    
  
  if ((point.y >= 0) && (point.y < properPosition)) {
      CGRect newRect = self.mapViewController.view.frame;
      newRect.origin.y = point.y;
      newRect.size.height = frame.size.height - point.y;
      [self.mapViewController.view setFrame: newRect];
  }
  }
