### ISSUE TITLE
viewWillAppear method is not called

### ISSUE THREAD

**Issue by magicdvd** [appunite/CLCascade#15]
i  follow the example code , create my own viewController extends the CLViewController, 

when i use  pushDetailViewController method , it  will just call  'viewDidLoad', the 'viewWillAppear' is not called.

is it a correct behavior of CLViewController?

**Comment by emilwojtaszek** [comment]
It should work on ios 5

**Comment by eliperkins** [comment]
I have noticed a similar behavior with the viewWillDisappear and viewWillUnload methods not being called in some CLViewControllers. I believe it is since their parent views (CLCascadeNavigationController, etc.) do not explicitly call or extend those methods.

**Comment by emilwojtaszek** [comment]
you can override this two methods, to achieve similar behaviours:
- (void)pageDidAppear;
- (void)pageDidDisappear;
