### ISSUE TITLE
CLCascadeView pushPage:fromPage:animated: ignores animated?

### ISSUE THREAD

**Issue by justinamberson** [appunite/CLCascade#20]
From the Categories Table View, calling setRootViewController:animated: to show the first page of the cascade stack seems to ignore the animated: variable.  Currently, setting animated: to YES or NO has no discernible effect.  All existing cascade views vanish immediately and is replaced by a new root cascade view.  I tried tracing it back through all the class implementations and can't find where the logic seems to fail.  It actually looks like there is no implementation for animation from reading over the code.  Is this a bug on my end, or am I correct?

I would prefer if the stack checked to see if any cascade views are present, animate those out, then animate in a new root cascade view. If possible, can you tell me the line where the new root cascade view is actually displayed on screen?

**Comment by emilwojtaszek** [comment]
done, check master
