### ISSUE TITLE
Duplicated implementation of the same message scrollViewDidEndScrollingAnimation

### ISSUE THREAD

**Issue by ForrestMobile** [appunite/CLCascade#31]
Duplicated implementation of the same message "- (void)scrollViewDidEndScrollingAnimation:(UIScrollView *)scrollView"
(file CLCascadeView.m)

See below:

///////////////////////////////////////////////////////////////////////////////////////////////////
- (void)scrollViewDidEndScrollingAnimation:(UIScrollView *)scrollView {
  [scrollView setPagingEnabled:NO];
  }

///////////////////////////////////////////////////////////////////////////////////////////////////
- (void)scrollViewDidEndDecelerating:(UIScrollView *)scrollView {
  if (_flags.isDetachPages) _flags.isDetachPages = NO;
  # ifdef CONTESTED_CASE
  
  [_scrollView setPagingEnabled: NO];
  # endif
  
  }

///////////////////////////////////////////////////////////////////////////////////////////////////
- (void)scrollViewDidEndScrollingAnimation:(UIScrollView *)scrollView {
  [_scrollView setPagingEnabled: YES];
  [_scrollView setPagingEnabled: NO];
  [_scrollView setScrollEnabled: YES];
  }

**Comment by emilwojtaszek** [comment]
done
