### ISSUE TITLE
Memory deallocation crash (Bad Access)

### ISSUE THREAD

**Issue by grgcombs** [appunite/CLCascade#4]
Start the cascade example app in portrait mode and select a few rows to stack up new tableview panels.

Now, rotate the interface to landscape and swipe a few panels off to the right in order to expose the very first panel.  

Now select any row ... observe the crash.

The call stack (from top to bottom) looks like the following:

```
[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:]
[ExampleTableViewController tableView:didSelectRowAtIndexPath:]
[CLViewController pushDetailViewController:animated:]
[CLCascadeNavigationController addViewController:sender:animated:]
[NSMutableArray removeObjectsInRange:]
[__NSArrayM removeObjectAtIndex:]
CFRelease
[ExampleTableViewController dealloc]
[CLTableViewController dealloc]
[CLViewController dealloc]
??
objc_msgSend
```

I tried doing a little error checking on line 229 of [CLCascadeNavigationController addViewController:sender:animated:] by including a check to make sure the index range was valid for the view controller array, but either I didn't get the conditions correct or that range wasn't the real problem.

**Comment by emilwojtaszek** [comment]
Done.

**Comment by mysticvalley** [comment]
Hey emilwojtaszek, can you please tell me how you solved this issue? I am also having same above issue in my iPad App. Thanks in advance, any word would be great help.
