### ISSUE TITLE
Graphic issue

### ISSUE THREAD

**Issue by chemicalweb** [appunite/CLCascade#8]
Try to:
1) tap on one categorie
2) tap on "New Web View"
4) tap on the First  view: "New Table View"
the root view go right.. near the second view pushed.
maybe is just a problem with the animation.

**Comment by emilwojtaszek** [comment]
check out last master

**Comment by ghost** [comment]
In latest lib there are some issues

1) tap on one category, then click on tableview, tap to right top one and then last one, all views removed from cascade.

Solution:
I just replace these lines:
    // pop all pages
    [_cascadeView popAllPagesAnimated: YES];
    // remove all controllers
    [_viewControllers removeAllObjects];

with these:
// index of last page
    NSUInteger index = [_viewControllers count] - 1;
    // pop page from back
    NSEnumerator\* enumerator = [_viewControllers reverseObjectEnumerator];
    // enumarate pages
    while ([enumerator nextObject] && _viewControllers.count > 1) {
        // pop page at index
        [cascadeView popPageAtIndex:index animated:NO];
        [_viewControllers removeLastObject];
        index--;
    }
    [cascadeView loadPageAtIndex:0];

and add this line in CLCascadeView at line number 236 in - (void) popPageAtIndex:(NSInteger)index animated:(BOOL)animated method:
// update content size
[self setProperContentSize];

**Comment by emilwojtaszek** [comment]
@mhamidg, corrected this error, thanks
@chemicalweb, I see what you mean, I'll handle this

**Comment by emilwojtaszek** [comment]
@chemicalweb, I think I managed to fix it, please check it

**Comment by ghost** [comment]
there is an issue in this build.
When user push multiple detail view controllers and if change the selection of root view controller (Where the texts are Category: ?) then you can see the effect of right side detail view controllers. sometime it crash and all other time is remove all other than first but first DVC is not on its position.

**Comment by ghost** [comment]
- (void)pageDidAppear
  method should also call with UIViewController's view life cycle method:
- (void)viewDidAppear:(BOOL)animated

and same as with Disappear

**Comment by emilwojtaszek** [comment]
When I move to iOS 5 and View Containers methods like viewWill/Did/Appear/Disappera will work properly.
